__cinderExport = {
  id: "gocomics",
  name: "GoComics",
  version: "1.0.0",
  icon: "📰",
  description: "Read daily comic strips from GoComics.com",
  contentType: "comics",

  capabilities: {
    search: true,
    discover: true,
    download: true,
  },

  // The full comic list (from the A‑Z page)
  ALL_COMICS: [
    {"name":"Mike Luckovich","featureId":256,"slug":"mikeluckovich"},
    {"name":"Andertoons","featureId":930,"slug":"andertoons"},
    {"name":"bacon","featureId":1520,"slug":"bacon"},
    {"name":"Birdbrains","featureId":30,"slug":"birdbrains"},
    {"name":"Big Top","featureId":220,"slug":"bigtop"},
    {"name":"Bird and Moon","featureId":1638,"slug":"bird-and-moon"},
    {"name":"Bliss","featureId":64,"slug":"bliss"},
    {"name":"Bloom County","featureId":213,"slug":"bloomcounty"},
    {"name":"The Boondocks","featureId":215,"slug":"boondocks"},
    {"name":"Dinosaur Comics","featureId":1322,"slug":"dinosaur-comics"},
    {"name":"Edge City","featureId":1495,"slug":"edge-city"},
    {"name":"Bo Nanas","featureId":217,"slug":"bonanas"},
    {"name":"Bob the Angry Flower","featureId":1732,"slug":"bob-the-angry-flower"},
    {"name":"Emmy Lou","featureId":1105,"slug":"emmy-lou"},
    {"name":"Bob the Squirrel","featureId":26,"slug":"bobthesquirrel"},
    {"name":"False Knees","featureId":1604,"slug":"false-knees"},
    {"name":"Flo and Friends","featureId":248,"slug":"floandfriends"},
    {"name":"Mike du Jour","featureId":1078,"slug":"mike-du-jour"},
    {"name":"Boomerangs","featureId":45,"slug":"boomerangs"},
    {"name":"Bottomliners","featureId":143,"slug":"bottomliners"},
    {"name":"Periquita","featureId":916,"slug":"periquita"},
    {"name":"Bound and Gagged","featureId":142,"slug":"boundandgagged"},
    {"name":"Brewster Rockit","featureId":104,"slug":"brewsterrockit"},
    {"name":"Berger & Wyse","featureId":1065,"slug":"berger-and-wyse"},
    {"name":"The Duplex","featureId":313,"slug":"duplex"},
    {"name":"For Better or For Worse","featureId":316,"slug":"forbetterorforworse"},
    {"name":"Grand Avenue","featureId":472,"slug":"grand-avenue"},
    {"name":"Alley Oop","featureId":805,"slug":"alley-oop"},
    {"name":"Tutelandia","featureId":152,"slug":"tutelandia"},
    {"name":"UFO","featureId":1745,"slug":"ufo"},
    {"name":"Mike Beckom","featureId":1728,"slug":"mike-beckom"},
    {"name":"Junk Drawer","featureId":1664,"slug":"junk-drawer"},
    {"name":"Long Story Short","featureId":1621,"slug":"long-story-short"},
    {"name":"Looks Good on Paper","featureId":1370,"slug":"looks-good-on-paper"},
    {"name":"Non Sequitur","featureId":182,"slug":"nonsequitur"},
    {"name":"Overboard","featureId":347,"slug":"overboard"},
    {"name":"Half Full","featureId":1259,"slug":"half-full"},
    {"name":"@Tavicat","featureId":1503,"slug":"tavicat"},
    {"name":"Betty","featureId":468,"slug":"betty"},
    {"name":"Animal Crackers","featureId":146,"slug":"animalcrackers"},
    {"name":"Aaggghhh","featureId":1614,"slug":"aaggghhh"},
    {"name":"Adult Children","featureId":1303,"slug":"adult-children"},
    {"name":"Agnes","featureId":233,"slug":"agnes"},
    {"name":"Ali's House","featureId":1519,"slug":"alis-house"},
    {"name":"Andy Capp","featureId":192,"slug":"andycapp"},
    {"name":"Angry Little Girls","featureId":905,"slug":"angry-little-girls"},
    {"name":"Annie","featureId":145,"slug":"annie"},
    {"name":"Arlo and Janis","featureId":467,"slug":"arloandjanis"},
    {"name":"Ask Shagg","featureId":235,"slug":"askshagg"},
    {"name":"Aunty Acid","featureId":1236,"slug":"aunty-acid"},
    {"name":"B.C.","featureId":193,"slug":"bc"},
    {"name":"Barkeater Lake","featureId":3,"slug":"barkeaterlake"},
    {"name":"Basic Instructions","featureId":36,"slug":"basicinstructions"},
    {"name":"Batch Rejection","featureId":1639,"slug":"batch-rejection"},
    {"name":"Beardo","featureId":1068,"slug":"beardo"},
    {"name":"Ben","featureId":874,"slug":"ben"},
    {"name":"Berkeley Mews","featureId":1353,"slug":"berkeley-mews"},
    {"name":"BFGF Syndrome","featureId":1593,"slug":"bfgf-syndrome"},
    {"name":"Bozo","featureId":1700,"slug":"bozo"},
    {"name":"Brevity","featureId":816,"slug":"brevity"},
    {"name":"Broom Hilda","featureId":140,"slug":"broomhilda"},
    {"name":"Barney & Clyde","featureId":624,"slug":"barneyandclyde"},
    {"name":"Bully","featureId":1305,"slug":"bully"},
    {"name":"Buckles","featureId":1192,"slug":"buckles"},
    {"name":"Cathy","featureId":170,"slug":"cathy"},
    {"name":"Chris Britt","featureId":74,"slug":"chrisbritt"},
    {"name":"C'est la Vie","featureId":37,"slug":"cestlavie"},
    {"name":"Cat's Cafe","featureId":1659,"slug":"cats-cafe"},
    {"name":"Chuck Draws Things","featureId":1667,"slug":"chuckdrawsthings"},
    {"name":"Chuckle Bros","featureId":59,"slug":"chucklebros"},
    {"name":"Citizen Dog","featureId":225,"slug":"citizendog"},
    {"name":"Clay Jones","featureId":242,"slug":"clayjones"},
    {"name":"CowTown","featureId":749,"slug":"cowtown"},
    {"name":"Catana Comics","featureId":1645,"slug":"little-moments-of-love"},
    {"name":"Curses!","featureId":1731,"slug":"curses"},
    {"name":"Daddy's Home","featureId":77,"slug":"daddyshome"},
    {"name":"Dark Side of the Horse","featureId":721,"slug":"darksideofthehorse"},
    {"name":"Eek!","featureId":28,"slug":"eek"},
    {"name":"Cathy Commiserations","featureId":1690,"slug":"cathy-commiserations"},
    {"name":"Cattitude — Doggonit","featureId":1498,"slug":"cattitude-doggonit"},
    {"name":"El Café de Poncho","featureId":156,"slug":"el-cafe-de-poncho"},
    {"name":"Endtown","featureId":751,"slug":"endtown"},
    {"name":"Cheer Up, Emo Kid","featureId":1581,"slug":"cheer-up-emo-kid"},
    {"name":"Crankshaft","featureId":271,"slug":"crankshaft"},
    {"name":"Dogs of C-Kennel","featureId":745,"slug":"dogsofckennel"},
    {"name":"Foolish Mortals","featureId":1076,"slug":"foolish-mortals"},
    {"name":"FoxTrot en Español","featureId":167,"slug":"foxtrotespanol"},
    {"name":"Drabble","featureId":470,"slug":"drabble"},
    {"name":"Nate el Grande","featureId":914,"slug":"nate-el-grande"},
    {"name":"Home and Away","featureId":76,"slug":"homeandaway"},
    {"name":"Ripley’s ¡Aunque Usted no lo Crea!","featureId":918,"slug":"ripleys-en-espanol"},
    {"name":"Peanuts en Español","featureId":758,"slug":"peanuts-espanol"},
    {"name":"Shen Comix","featureId":1497,"slug":"shen-comix"},
    {"name":"Tarzán en Español","featureId":920,"slug":"tarzan-en-espanol"},
    {"name":"The Wandering Melon","featureId":1313,"slug":"the-wandering-melon"},
    {"name":"Win, Lose, Drew","featureId":813,"slug":"drewlitton"},
    {"name":"Eric Allie","featureId":1729,"slug":"eric-allie"},
    {"name":"Wondermark","featureId":1515,"slug":"wondermark"},
    {"name":"Los Osorios","featureId":915,"slug":"los-osorios"},
    {"name":"Marshall Ramsey","featureId":72,"slug":"marshallramsey"},
    {"name":"Bill Bramhall","featureId":1746,"slug":"bill-bramhall"},
    {"name":"Bob Gorrell","featureId":237,"slug":"bobgorrell"},
    {"name":"Garfield en Español","featureId":448,"slug":"garfieldespanol"},
    {"name":"Brian McFadden","featureId":1289,"slug":"brian-mcfadden"},
    {"name":"Chip Bok","featureId":239,"slug":"chipbok"},
    {"name":"Jerry King Comics","featureId":1725,"slug":"jerry-king-comics"},
    {"name":"Heathcliff en Español","featureId":484,"slug":"heathcliffespanol"},
    {"name":"Justo y Franco","featureId":910,"slug":"justo-y-franco"},
    {"name":"The K Chronicles","featureId":337,"slug":"thekchronicles"},
    {"name":"Lio en Español","featureId":161,"slug":"lioespanol"},
    {"name":"Lola en Español","featureId":911,"slug":"lola-en-espanol"},
    {"name":"Mannequin on the Moon","featureId":1698,"slug":"mannequin-on-the-moon"},
    {"name":"Banana Triangle","featureId":903,"slug":"banana-triangle"},
    {"name":"Gaturro","featureId":166,"slug":"gaturro"},
    {"name":"Gil","featureId":1471,"slug":"gil"},
    {"name":"Gasoline Alley","featureId":124,"slug":"gasolinealley"},
    {"name":"Drew Sheneman","featureId":128,"slug":"drewsheneman"},
    {"name":"Cornered","featureId":39,"slug":"cornered"},
    {"name":"Claw","featureId":1500,"slug":"claw"},
    {"name":"Cleats","featureId":228,"slug":"cleats"},
    {"name":"Compu-toon","featureId":1,"slug":"compu-toon"},
    {"name":"Crumb","featureId":944,"slug":"crumb"},
    {"name":"DeFlocked","featureId":1196,"slug":"deflocked"},
    {"name":"Diamond Lil","featureId":746,"slug":"diamondlil"},
    {"name":"Geech","featureId":819,"slug":"geech"},
    {"name":"Dog Eat Doug","featureId":244,"slug":"dogeatdoug"},
    {"name":"Domestic Abuse","featureId":44,"slug":"domesticabuse"},
    {"name":"F Minus","featureId":814,"slug":"fminus"},
    {"name":"Doodle for Food","featureId":1562,"slug":"doodle-for-food"},
    {"name":"Doodle Town","featureId":1290,"slug":"doodle-town"},
    {"name":"Fred Basset","featureId":125,"slug":"fredbasset"},
    {"name":"Free Range","featureId":66,"slug":"freerange"},
    {"name":"Get Fuzzy","featureId":473,"slug":"getfuzzy"},
    {"name":"Gary Markstein","featureId":73,"slug":"garymarkstein"},
    {"name":"Family Tree","featureId":785,"slug":"familytree"},
    {"name":"Joe Heller","featureId":946,"slug":"joe-heller"},
    {"name":"Four Eyes","featureId":1267,"slug":"four-eyes"},
    {"name":"Francis","featureId":1297,"slug":"francis"},
    {"name":"Kevin Kallaugher","featureId":408,"slug":"kal"},
    {"name":"Matt Bors","featureId":852,"slug":"matt-bors"},
    {"name":"Heathcliff","featureId":251,"slug":"heathcliff"},
    {"name":"Freshly Squeezed","featureId":776,"slug":"freshlysqueezed"},
    {"name":"Herb and Jamaal","featureId":194,"slug":"herbandjamaal"},
    {"name":"Funky Winkerbean","featureId":1198,"slug":"funky-winkerbean"},
    {"name":"Peanuts Begins","featureId":1357,"slug":"peanuts-begins"},
    {"name":"Matt Wuerker","featureId":762,"slug":"mattwuerker"},
    {"name":"Tex","featureId":1724,"slug":"tex"},
    {"name":"Ike","featureId":493,"slug":"backintheday"},
    {"name":"Trucutú","featureId":921,"slug":"trucutu"},
    {"name":"Joey Weatherford","featureId":1747,"slug":"joey-weatherford"},
    {"name":"Michael Ramirez","featureId":67,"slug":"michaelramirez"},
    {"name":"Dana Summers","featureId":127,"slug":"danasummers"},
    {"name":"Jim Morin","featureId":409,"slug":"jimmorin"},
    {"name":"John Deering","featureId":252,"slug":"johndeering"},
    {"name":"ViewsAfrica","featureId":429,"slug":"viewsafrica"},
    {"name":"Green Humour","featureId":1275,"slug":"green-humour"},
    {"name":"Baldo en Español","featureId":345,"slug":"baldoespanol"},
    {"name":"Hot Comics for Cool People","featureId":1468,"slug":"hot-comics-for-cool-people"},
    {"name":"Hutch Owen","featureId":1104,"slug":"hutch-owen"},
    {"name":"Imagine This","featureId":2,"slug":"imaginethis"},
    {"name":"Invisible Bread","featureId":1119,"slug":"invisible-bread"},
    {"name":"Jane's World","featureId":767,"slug":"janesworld"},
    {"name":"Kid Beowulf","featureId":1315,"slug":"kid-beowulf"},
    {"name":"9 to 5","featureId":109,"slug":"9to5"},
    {"name":"Kitchen Capers","featureId":956,"slug":"kitchen-capers"},
    {"name":"Kliban's Cats","featureId":951,"slug":"klibans-cats"},
    {"name":"Laughing Redhead Comics","featureId":1591,"slug":"laughing-redhead-comics"},
    {"name":"Learn to Speak Cat","featureId":1360,"slug":"learn-to-speak-cat"},
    {"name":"Lio","featureId":162,"slug":"lio"},
    {"name":"Little Dog Lost","featureId":89,"slug":"littledoglost"},
    {"name":"Lola","featureId":118,"slug":"lola"},
    {"name":"Crabgrass","featureId":1660,"slug":"crabgrass"},
    {"name":"Get a Life","featureId":495,"slug":"getalife"},
    {"name":"Ginger Meggs en Español","featureId":449,"slug":"gingermeggs-espanol"},
    {"name":"Ink Pen","featureId":332,"slug":"inkpen"},
    {"name":"Last Kiss","featureId":51,"slug":"lastkiss"},
    {"name":"Cow and Boy Classics","featureId":784,"slug":"cowandboy"},
    {"name":"Calvin and Hobbes en Español","featureId":169,"slug":"calvinandhobbesespanol"},
    {"name":"Fat Cats","featureId":823,"slug":"fat-cats"},
    {"name":"Farcus","featureId":818,"slug":"farcus"},
    {"name":"For Heaven's Sake","featureId":247,"slug":"forheavenssake"},
    {"name":"Gary Varvel","featureId":250,"slug":"garyvarvel"},
    {"name":"Frog Applause","featureId":20,"slug":"frogapplause"},
    {"name":"Frazz","featureId":471,"slug":"frazz"},
    {"name":"G-Man Webcomics","featureId":1416,"slug":"g-man-webcomics"},
    {"name":"Jack Ohman","featureId":120,"slug":"jackohman"},
    {"name":"Jeff Danziger","featureId":40,"slug":"jeffdanziger"},
    {"name":"The Meaning of Lila","featureId":255,"slug":"meaningoflila"},
    {"name":"Messycow Comics","featureId":1636,"slug":"messy-cow"},
    {"name":"Mexikid Stories","featureId":1663,"slug":"mexikid-stories"},
    {"name":"Lunarbaboon","featureId":1455,"slug":"lunarbaboon"},
    {"name":"Nancy Classics","featureId":1363,"slug":"nancy-classics"},
    {"name":"Herman","featureId":769,"slug":"herman"},
    {"name":"Origins of the Sunday Comics","featureId":1249,"slug":"origins-of-the-sunday-comics"},
    {"name":"Jen Sorensen","featureId":18,"slug":"jen-sorensen"},
    {"name":"Joel Pett","featureId":335,"slug":"joelpett"},
    {"name":"Ozy and Millie","featureId":1109,"slug":"ozy-and-millie"},
    {"name":"Shirley and Son Classics","featureId":822,"slug":"shirley-and-son-classics"},
    {"name":"Phil Hands","featureId":1265,"slug":"phil-hands"},
    {"name":"Rebecca Hendin","featureId":1368,"slug":"rebecca-hendin"},
    {"name":"FoxTrot","featureId":346,"slug":"foxtrot"},
    {"name":"Imogen Quest","featureId":1579,"slug":"imogen-quest"},
    {"name":"Bad Machinery: Solver","featureId":1493,"slug":"bad-machinery"},
    {"name":"The Upside Down World of Gustave Verbeek","featureId":1563,"slug":"upside-down-world-of-gustave-verbeek"},
    {"name":"In Security","featureId":1564,"slug":"in-security"},
    {"name":"In the Bleachers","featureId":212,"slug":"inthebleachers"},
    {"name":"Worry Lines","featureId":1710,"slug":"worry-lines"},
    {"name":"WuMo en Español","featureId":1321,"slug":"wumoespanol"},
    {"name":"In the Sticks","featureId":465,"slug":"inthesticks"},
    {"name":"Heart of the City","featureId":330,"slug":"heartofthecity"},
    {"name":"Jake Likes Onions","featureId":1603,"slug":"jake-likes-onions"},
    {"name":"JumpStart","featureId":474,"slug":"jumpstart"},
    {"name":"La Cucaracha en Español","featureId":1270,"slug":"la-cucaracha-en-espanol"},
    {"name":"Yeah It’s Chill","featureId":1748,"slug":"yeah-its-chill"},
    {"name":"Goats","featureId":1428,"slug":"goats"},
    {"name":"Wizard of Id Classics","featureId":1347,"slug":"wizard-of-id-classics"},
    {"name":"Lay Lines","featureId":1361,"slug":"lay-lines"},
    {"name":"Li'l Abner","featureId":896,"slug":"lil-abner"},
    {"name":"Life on Earth","featureId":1613,"slug":"life-on-earth"},
    {"name":"Amanda the Great","featureId":1561,"slug":"amanda-the-great"},
    {"name":"Benitin y Eneas","featureId":159,"slug":"muttandjeffespanol"},
    {"name":"Little Nemo","featureId":1237,"slug":"little-nemo"},
    {"name":"Liz Climo Cartoons","featureId":1554,"slug":"liz-climo-cartoons"},
    {"name":"Medium Large","featureId":1077,"slug":"medium-large"},
    {"name":"Gil Thorp","featureId":123,"slug":"gilthorp"},
    {"name":"Ginger Meggs","featureId":32,"slug":"gingermeggs"},
    {"name":"Glasbergen Cartoons","featureId":1319,"slug":"glasbergen-cartoons"},
    {"name":"Globetrotter","featureId":1714,"slug":"globetrotter"},
    {"name":"Gray Matters","featureId":953,"slug":"gray-matters"},
    {"name":"Haircut Practice","featureId":1669,"slug":"haircut-practice"},
    {"name":"Harley","featureId":1576,"slug":"harley"},
    {"name":"Al Goodwyn Editorial Cartoons","featureId":1694,"slug":"algoodwyn"},
    {"name":"Henry Payne","featureId":808,"slug":"henrypayne"},
    {"name":"Dick Tracy","featureId":134,"slug":"dicktracy"},
    {"name":"The Elderberries","featureId":314,"slug":"theelderberries"},
    {"name":"Miss Peach","featureId":1641,"slug":"miss-peach"},
    {"name":"Matt Davies","featureId":116,"slug":"mattdavies"},
    {"name":"Day by Dave","featureId":1733,"slug":"day-by-dave"},
    {"name":"Momma","featureId":257,"slug":"momma"},
    {"name":"Monty Diaros","featureId":913,"slug":"monty-diaros"},
    {"name":"Liberty Meadows","featureId":254,"slug":"libertymeadows"},
    {"name":"Loose Parts","featureId":117,"slug":"looseparts"},
    {"name":"Motley Classics","featureId":821,"slug":"motley-classics"},
    {"name":"Lost Sheep","featureId":340,"slug":"lostsheep"},
    {"name":"Luann en Español","featureId":1318,"slug":"luannspanish"},
    {"name":"Rob Rogers","featureId":811,"slug":"robrogers"},
    {"name":"Mr. Lowe","featureId":1369,"slug":"mr-lowe"},
    {"name":"Lucky Cow","featureId":341,"slug":"luckycow"},
    {"name":"Maintaining","featureId":191,"slug":"maintaining"},
    {"name":"Maria's Day","featureId":1062,"slug":"marias-day"},
    {"name":"Marmaduke","featureId":476,"slug":"marmaduke"},
    {"name":"Monty","featureId":779,"slug":"monty"},
    {"name":"Mutt & Jeff","featureId":184,"slug":"muttandjeff"},
    {"name":"My Dad is Dracula","featureId":1633,"slug":"my-dad-is-dracula"},
    {"name":"Lalo Alcaraz","featureId":164,"slug":"laloalcaraz"},
    {"name":"Pickles","featureId":85,"slug":"pickles"},
    {"name":"Reality Check","featureId":801,"slug":"realitycheck"},
    {"name":"MythTickle","featureId":31,"slug":"mythtickle"},
    {"name":"Nest Heads","featureId":231,"slug":"nestheads"},
    {"name":"NEUROTICA","featureId":23,"slug":"neurotica"},
    {"name":"Next Door Neighbors","featureId":1502,"slug":"next-door-neighbors"},
    {"name":"Nick and Zuzu","featureId":1103,"slug":"nick-and-zuzu"},
    {"name":"M2Bulls","featureId":1615,"slug":"m2bulls"},
    {"name":"Nothing is Not Something","featureId":1090,"slug":"nothing-is-not-something"},
    {"name":"Back to B.C.","featureId":1427,"slug":"back-to-bc"},
    {"name":"Now Recharging","featureId":1548,"slug":"now-recharging"},
    {"name":"On A Claire Day","featureId":259,"slug":"onaclaireday"},
    {"name":"Our Super Adventure","featureId":1662,"slug":"our-super-adventure"},
    {"name":"Outland","featureId":1611,"slug":"outland"},
    {"name":"Pibgorn","featureId":10,"slug":"pibgorn"},
    {"name":"Pibgorn Sketches","featureId":11,"slug":"pibgornsketches"},
    {"name":"Please Listen to Me","featureId":1469,"slug":"please-listen-to-me"},
    {"name":"Poorcraft","featureId":1530,"slug":"poorcraft"},
    {"name":"Pot-Shots","featureId":1375,"slug":"pot-shots"},
    {"name":"PreTeena","featureId":176,"slug":"preteena"},
    {"name":"Prickly City","featureId":177,"slug":"pricklycity"},
    {"name":"Raising Duncan","featureId":899,"slug":"raising-duncan"},
    {"name":"Randolph Itch, 2 a.m.","featureId":958,"slug":"randolphitch"},
    {"name":"Real Life Adventures","featureId":173,"slug":"reallifeadventures"},
    {"name":"Red Meat","featureId":174,"slug":"redmeat"},
    {"name":"Richard's Poor Almanac","featureId":1094,"slug":"richards-poor-almanac"},
    {"name":"Poorly Drawn Lines","featureId":1264,"slug":"poorly-drawn-lines"},
    {"name":"Oh, Brother!","featureId":1292,"slug":"oh-brother"},
    {"name":"Out of the Gene Pool","featureId":92,"slug":"outofthegenepool"},
    {"name":"Scary Gary","featureId":58,"slug":"scarygary"},
    {"name":"Over the Hedge","featureId":477,"slug":"overthehedge"},
    {"name":"Rabbits Against Magic","featureId":52,"slug":"rabbitsagainstmagic"},
    {"name":"Nick Anderson","featureId":87,"slug":"nickanderson"},
    {"name":"Robert Ariail","featureId":812,"slug":"robert-ariail"},
    {"name":"Clay Bennett","featureId":80,"slug":"claybennett"},
    {"name":"Lisa Benson","featureId":90,"slug":"lisabenson"},
    {"name":"Scott Stantis","featureId":70,"slug":"scottstantis"},
    {"name":"Ted Rall","featureId":97,"slug":"ted-rall"},
    {"name":"Tom the Dancing Bug","featureId":148,"slug":"tomthedancingbug"},
    {"name":"The Martian Confederacy","featureId":1314,"slug":"the-martian-confederacy"},
    {"name":"Don Brutus","featureId":907,"slug":"don-brutus"},
    {"name":"Eyebeam","featureId":1488,"slug":"eyebeam"},
    {"name":"The Born Loser","featureId":469,"slug":"the-born-loser"},
    {"name":"The Flying McCoys","featureId":318,"slug":"theflyingmccoys"},
    {"name":"The Middle Age","featureId":1589,"slug":"the-middle-age"},
    {"name":"The Middletons","featureId":113,"slug":"themiddletons"},
    {"name":"The Norm Classics","featureId":22,"slug":"thenorm"},
    {"name":"One Big Happy","featureId":258,"slug":"onebighappy"},
    {"name":"Rose Is Rose","featureId":478,"slug":"roseisrose"},
    {"name":"Rip Haywire","featureId":775,"slug":"riphaywire"},
    {"name":"Robbie and Bobby","featureId":1240,"slug":"robbie-and-bobby"},
    {"name":"Texts From Mittens","featureId":1626,"slug":"texts-from-mittens"},
    {"name":"Saturday Morning Breakfast Cereal","featureId":1317,"slug":"saturday-morning-breakfast-cereal"},
    {"name":"That New Carl Smell","featureId":1257,"slug":"that-new-carl-smell"},
    {"name":"WaynoVision","featureId":1326,"slug":"waynovision"},
    {"name":"Perlas Para Los Cerdos","featureId":917,"slug":"perlas-para-los-cerdos"},
    {"name":"Rubes","featureId":261,"slug":"rubes"},
    {"name":"The Knight Life","featureId":799,"slug":"theknightlife"},
    {"name":"Savage Chickens","featureId":1056,"slug":"savage-chickens"},
    {"name":"Shoe","featureId":50,"slug":"shoe"},
    {"name":"Sketchshark Comics","featureId":1528,"slug":"sketchshark-comics"},
    {"name":"Skin Horse","featureId":47,"slug":"skinhorse"},
    {"name":"Skippy","featureId":1075,"slug":"skippy"},
    {"name":"Small Potatoes","featureId":1549,"slug":"small-potatoes"},
    {"name":"Snow Sez","featureId":1429,"slug":"snow-sez"},
    {"name":"Spot the Frog","featureId":897,"slug":"spot-the-frog"},
    {"name":"Sticky Comics","featureId":1482,"slug":"sticky-comics"},
    {"name":"Studio Jantze","featureId":1696,"slug":"studio-jantze"},
    {"name":"Sunny Street","featureId":1229,"slug":"sunny-street"},
    {"name":"Super-Fun-Pak Comix","featureId":1306,"slug":"super-fun-pak-comix"},
    {"name":"Swan Eaters","featureId":1646,"slug":"swan-eaters"},
    {"name":"Sweet and Sour Pork","featureId":1258,"slug":"sweet-and-sour-pork"},
    {"name":"Sylvia","featureId":101,"slug":"sylvia"},
    {"name":"Tarzan","featureId":774,"slug":"tarzan"},
    {"name":"Ten Cats","featureId":943,"slug":"ten-cats"},
    {"name":"That is Priceless","featureId":940,"slug":"that-is-priceless"},
    {"name":"Understanding Chaos","featureId":1274,"slug":"understanding-chaos"},
    {"name":"Watch Your Head","featureId":82,"slug":"watchyourhead"},
    {"name":"Wawawiwa","featureId":1673,"slug":"wawawiwa"},
    {"name":"Wee Pals","featureId":267,"slug":"weepals"},
    {"name":"Widdershins","featureId":1518,"slug":"widdershins"},
    {"name":"Wide Open!","featureId":1081,"slug":"wide-open"},
    {"name":"The Worried Well","featureId":1475,"slug":"the-worried-well"},
    {"name":"Ziggy en Español","featureId":450,"slug":"ziggyespanol"},
    {"name":"Speed Bump","featureId":265,"slug":"speedbump"},
    {"name":"Strange Brew","featureId":266,"slug":"strangebrew"},
    {"name":"Steve Benson","featureId":262,"slug":"stevebenson"},
    {"name":"Steve Breen","featureId":68,"slug":"stevebreen"},
    {"name":"Steve Kelley","featureId":263,"slug":"stevekelley"},
    {"name":"Tim Campbell","featureId":1595,"slug":"tim-campbell"},
    {"name":"ViewsAsia","featureId":431,"slug":"viewsasia"},
    {"name":"(th)ink","featureId":147,"slug":"think"},
    {"name":"Pat Oliphant","featureId":179,"slug":"patoliphant"},
    {"name":"The Big Picture","featureId":209,"slug":"thebigpicture"},
    {"name":"Pedro X. Molina","featureId":1720,"slug":"pedroxmolina"},
    {"name":"Tom Toles","featureId":94,"slug":"tomtoles"},
    {"name":"The Barn","featureId":60,"slug":"thebarn"},
    {"name":"The City","featureId":42,"slug":"thecity"},
    {"name":"Deep Dark Fears","featureId":1304,"slug":"deep-dark-fears"},
    {"name":"The Dinette Set","featureId":243,"slug":"dinetteset"},
    {"name":"Fred Basset en Español","featureId":168,"slug":"fredbassetespanol"},
    {"name":"The Fusco Brothers","featureId":320,"slug":"thefuscobrothers"},
    {"name":"Ordinary Bill","featureId":1071,"slug":"ordinary-bill"},
    {"name":"The Humble Stumble","featureId":902,"slug":"humble-stumble"},
    {"name":"Kliban","featureId":950,"slug":"kliban"},
    {"name":"Lard's World Peace Tips","featureId":1298,"slug":"lards-world-peace-tips"},
    {"name":"Las Hermanas Stone","featureId":742,"slug":"stonesoup_espanol"},
    {"name":"Luann Againn","featureId":1125,"slug":"luann-againn"},
    {"name":"Moderately Confused","featureId":802,"slug":"moderately-confused"},
    {"name":"Peanuts","featureId":757,"slug":"peanuts"},
    {"name":"Overboard en Español","featureId":158,"slug":"overboardespanol"},
    {"name":"Pluggers","featureId":107,"slug":"pluggers"},
    {"name":"Scenes from a Multiverse","featureId":1421,"slug":"scenes-from-a-multiverse"},
    {"name":"The Grizzwells","featureId":326,"slug":"thegrizzwells"},
    {"name":"Thatababy","featureId":738,"slug":"thatababy"},
    {"name":"Spirit of the Staircase","featureId":1550,"slug":"spirit-of-the-staircase"},
    {"name":"Warped","featureId":1531,"slug":"warped"},
    {"name":"Tiny Sepuku","featureId":21,"slug":"tinysepuku"},
    {"name":"Today's Szep","featureId":1692,"slug":"todays-szep"},
    {"name":"Unstrange Phenomena","featureId":825,"slug":"unstrange-phenomena"},
    {"name":"Viivi & Wagner","featureId":1058,"slug":"viivi-and-wagner"},
    {"name":"Zack Hill","featureId":270,"slug":"zackhill"},
    {"name":"A Problem Like Jamal","featureId":1643,"slug":"a-problem-like-jamal"},
    {"name":"The Academia Waltz","featureId":203,"slug":"the-academia-waltz"},
    {"name":"The Argyle Sweater","featureId":12,"slug":"theargylesweater"},
    {"name":"Art by Moga","featureId":1716,"slug":"artbymoga"},
    {"name":"The Awkward Yeti","featureId":1323,"slug":"the-awkward-yeti"},
    {"name":"Ballard Street","featureId":236,"slug":"ballardstreet"},
    {"name":"W.T. Duck","featureId":62,"slug":"wtduck"},
    {"name":"Wizard of Id en Español","featureId":199,"slug":"wizardofidespanol"},
    {"name":"Working It Out","featureId":269,"slug":"workingitout"},
    {"name":"Wrong Hands","featureId":1364,"slug":"wrong-hands"},
    {"name":"Yaffle","featureId":1631,"slug":"yaffle"},
    {"name":"Yes, I'm Hot in This","featureId":1677,"slug":"yesimhotinthis"},
    {"name":"Zen Pencils","featureId":1251,"slug":"zen-pencils"},
    {"name":"Wizard of Id","featureId":198,"slug":"wizardofid"},
    {"name":"The Lockhorns","featureId":1204,"slug":"lockhorns"},
    {"name":"Tank McNamara","featureId":98,"slug":"tankmcnamara"},
    {"name":"Working Daze","featureId":826,"slug":"working-daze"},
    {"name":"WuMo","featureId":1247,"slug":"wumo"},
    {"name":"Two Party Opera","featureId":1583,"slug":"two-party-opera"},
    {"name":"Views of the World","featureId":435,"slug":"viewsoftheworld"},
    {"name":"ViewsAmerica","featureId":430,"slug":"viewsamerica"},
    {"name":"ViewsBusiness","featureId":437,"slug":"viewsbusiness"},
    {"name":"ViewsEurope","featureId":432,"slug":"viewseurope"},
    {"name":"ViewsLatinAmerica","featureId":433,"slug":"viewslatinamerica"},
    {"name":"ViewsMidEast","featureId":434,"slug":"viewsmideast"},
    {"name":"Jeff Stahler","featureId":809,"slug":"jeffstahler"},
    {"name":"Kevin Necessary Editorial Cartoons","featureId":1606,"slug":"kevin-necessary-editorial-cartoons"},
    {"name":"The Buckets","featureId":800,"slug":"thebuckets"},
    {"name":"Bleeker: The Rechargeable Dog","featureId":25,"slug":"bleeker"},
    {"name":"Bloom County Continues","featureId":1422,"slug":"bloom-county"},
    {"name":"Mike Lester","featureId":932,"slug":"mike-lester"},
    {"name":"Calvin and Hobbes","featureId":344,"slug":"calvinandhobbes"},
    {"name":"Buni","featureId":901,"slug":"buni"},
    {"name":"Close to Home","featureId":227,"slug":"closetohome"},
    {"name":"Cul de Sac","featureId":226,"slug":"culdesac"},
    {"name":"Doonesbury","featureId":311,"slug":"doonesbury"},
    {"name":"Frank and Ernest","featureId":315,"slug":"frank-and-ernest"},
    {"name":"The Comic Strip That Has A Finale Every Day","featureId":1406,"slug":"the-comic-strip-that-has-a-finale-every-day"},
    {"name":"The Daily Drawing","featureId":1359,"slug":"the-daily-drawing"},
    {"name":"The Doozies","featureId":48,"slug":"thedoozies"},
    {"name":"Phoebe and Her Unicorn","featureId":955,"slug":"phoebe-and-her-unicorn"},
    {"name":"Fowl Language","featureId":1460,"slug":"fowl-language"},
    {"name":"FurBabies","featureId":1741,"slug":"furbabies"},
    {"name":"Jim Benton Cartoons","featureId":1333,"slug":"jim-benton-cartoons"},
    {"name":"Pooch Café","featureId":348,"slug":"poochcafe"},
    {"name":"Molly and the Bear","featureId":755,"slug":"molly-and-the-bear"},
    {"name":"Mother Goose and Grimm","featureId":1735,"slug":"mother-goose-and-grimm"},
    {"name":"New Adventures of Queen Victoria","featureId":16,"slug":"thenewadventuresofqueenvictoria"},
    {"name":"It's All About You","featureId":91,"slug":"itsallaboutyou"},
    {"name":"Little Fried Chicken and Sushi","featureId":1309,"slug":"little-fried-chicken-and-sushi"},
    {"name":"Big Nate","featureId":777,"slug":"bignate"},
    {"name":"Off the Mark","featureId":792,"slug":"offthemark"},
    {"name":"The Other Coast","featureId":196,"slug":"theothercoast"},
    {"name":"Red and Rover","featureId":84,"slug":"redandrover"},
    {"name":"Ripley's Believe It or Not","featureId":778,"slug":"ripleysbelieveitornot"},
    {"name":"Sarah's Scribbles","featureId":1286,"slug":"sarahs-scribbles"},
    {"name":"Not Invented Here","featureId":1470,"slug":"not-invented-here"},
    {"name":"Questionable Quotebook","featureId":1480,"slug":"questionable-quotebook"},
    {"name":"Perry Bible Fellowship","featureId":1346,"slug":"perry-bible-fellowship"},
    {"name":"Sherman's Lagoon","featureId":1715,"slug":"shermanslagoon"},
    {"name":"Luann","featureId":475,"slug":"luann"},
    {"name":"1 and Done","featureId":1424,"slug":"1-and-done"},
    {"name":"Thin Lines","featureId":496,"slug":"thinlines"},
    {"name":"Ziggy","featureId":81,"slug":"ziggy"},
    {"name":"Stone Soup","featureId":1453,"slug":"stonesoup"},
    {"name":"Walt Handelsman","featureId":100,"slug":"walthandelsman"},
    {"name":"Baby Blues","featureId":1712,"slug":"babyblues"},
    {"name":"9 Chickweed Lane","featureId":358,"slug":"9-chickweed-lane"},
    {"name":"Adam@Home","featureId":200,"slug":"adamathome"},
    {"name":"The Adventures of Business Cat","featureId":1372,"slug":"the-adventures-of-business-cat"},
    {"name":"AJ and Magnus","featureId":1516,"slug":"aj-and-magnus"},
    {"name":"Baldo","featureId":204,"slug":"baldo"},
    {"name":"Breaking Cat News","featureId":1330,"slug":"breaking-cat-news"},
    {"name":"Home Free","featureId":1719,"slug":"homefree"},
    {"name":"FoxTrot Classics","featureId":319,"slug":"foxtrotclassics"},
    {"name":"Ollie and Quentin","featureId":1067,"slug":"ollie-and-quentin"},
    {"name":"Street Scene","featureId":1764,"slug":"street-scene"},
    {"name":"Nancy","featureId":806,"slug":"nancy"},
    {"name":"Garfield","featureId":322,"slug":"garfield"},
    {"name":"The Ancients","featureId":1763,"slug":"the-ancients"},
    {"name":"Too Much Coffee Man","featureId":38,"slug":"toomuchcoffeeman"},
    {"name":"Underpants and Overbites","featureId":1665,"slug":"underpants-and-overbites"},
    {"name":"Wallace the Brave","featureId":1411,"slug":"wallace-the-brave"},
    {"name":"Lug Nuts","featureId":1320,"slug":"lug-nuts"},
    {"name":"Pearls Before Swine","featureId":479,"slug":"pearlsbeforeswine"},
    {"name":"La Cucaracha","featureId":339,"slug":"lacucaracha"}
  ],

  async search(query, page) {
    let comics = this.ALL_COMICS;
    let lowerQuery = query.toLowerCase();
    let filtered = comics.filter(comic =>
      comic.name && comic.name.toLowerCase().includes(lowerQuery)
    );
    let pageSize = 20;
    let start = page * pageSize;
    let paged = filtered.slice(start, start + pageSize);
    return paged.map(comic => ({
      id: comic.slug,
      title: comic.name,
      author: "",
      cover: "https://avatar.amuniversal.com/feature_avatars/recommendation?feature=" + comic.slug,
      url: "https://www.gocomics.com/" + comic.slug,
      format: "comics"
    }));
  },

  async resolve(item) {
    let today = new Date();
    let yyyy = today.getFullYear();
    let mm = (today.getMonth() + 1).toString().padStart(2, '0');
    let dd = today.getDate().toString().padStart(2, '0');
    let pageUrl = `https://www.gocomics.com/${item.id}/${yyyy}/${mm}/${dd}`;

    let response = await cinder.fetch(pageUrl, {
      headers: { "User-Agent": "CinderApp/1.0" }
    });
    if (response.status !== 200) {
      throw new Error("Failed to load comic page: " + response.status);
    }

    let html = response.data;
    let imgMatch = html.match(/<img\s[^>]*class="img-fluid"[^>]*src="(https:\/\/[^"]+)"/i);
    if (imgMatch) return { url: imgMatch[1] };

    let fallbackMatch = html.match(/<picture[^>]*>.*?<img[^>]*src="(https:\/\/[^"]+)"/is);
    if (fallbackMatch) return { url: fallbackMatch[1] };

    throw new Error("Could not find comic image on the page.");
  }
};